theme: jekyll-theme-slate
future: true
title: Welcome to 14 Lectures on Visual SLAM: From Theory to Practice, by Xiang Gao, Tao Zhang, Qinrui Yan and Yi Liu
description: This is the English version of this book. If you are a Chinese reader, please check [this page](https://item.jd.com/12077296218.html). Our code is in github: [code](https://github.com/gaoxiang12/slambook).
